apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.database.name | quote }}
  POSTGRES_USER: {{ .Values.postgres.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.database.password | quote }}